### ISSUE TITLE
[ error ] ofxMQTT: Loop error: The connection was lost.

### ISSUE THREAD

**Issue by huyyoo** [256dpi/ofxMQTT#10]
I make a client subscribed to 5 topics at the same time. The publisher is a python mqtt. It sent the data 0.1s a time. When the openframeworks run a period of time, it would come up with the following Error: "ofxMQTT: Loop error: The connection was lost."

Is there any way I can solve this problem, for example, auto-reconnect the broker?

**Comment by huyyoo** [comment]
When I slow down the rate to send the data, like 0.5s a time, it would work just be fine. But is there any way I can send the data faster(0.05s or 0.1s), without causing the Error:"Loop error: The connection was lost"

**Comment by 256dpi** [comment]
This was most likely due to a rate limit on the broker. Close due to age.
